version: "3.7"
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
      - client

  client:
    container_name: dva_client
    hostname: dva_client
    image: dva_client
    build:
      context: ./services/client
      dockerfile: Dockerfile.dev
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  server:
    container_name: dva_server
    hostname: dva_server
    image: dva_server
    build:
      context: ./services/server
      dockerfile: Dockerfile.dev
    volumes:
      - "./services/server:/usr/src/app"
    ports:
      - 8000:8000
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev_db
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/dev_test_db
    depends_on:
      - db

  db:
    container_name: dva_db
    hostname: dva_db
    image: dva_db
    build:
      context: ./services/db
      dockerfile: Dockerfile.dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
