# Generated by Django 2.2.6 on 2020-04-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200405_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexesday',
            name='datetime_epoch',
            field=models.BigIntegerField(),
        ),
    ]
