# base image
FROM node:12.13.1-alpine

# set working directory
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
COPY yarn.lock /usr/src/app/yarn.lock
RUN yarn global add typescript --silent
RUN yarn global add react-scripts --silent
RUN yarn install

EXPOSE 3000

# start app
CMD ["yarn", "start"]