# Generated by Django 2.2.6 on 2020-04-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexesday',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='indexesmin',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nasdaqday',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nasdaqmin',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nyseday',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nysemin',
            name='datetime',
            field=models.DateField(null=True),
        ),
    ]
