# Generated by Django 2.2.6 on 2020-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200405_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexesmin',
            name='datetime_epoch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nasdaqday',
            name='datetime_epoch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nasdaqmin',
            name='datetime_epoch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nyseday',
            name='datetime_epoch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nysemin',
            name='datetime_epoch',
            field=models.BigIntegerField(),
        ),
    ]
