# Generated by Django 3.0.4 on 2020-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20200405_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamental',
            name='high52',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fundamental',
            name='low52',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
